local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/AikaV3rm/UiLib/master/Lib.lua')))()

local w = library:CreateWindow("Crazy Hub") -- Creates the window

local b = w:CreateFolder("Science Simulator") -- Creates the folder(U will put here your buttons,etc)

b:Label("Scripts",{
    TextSize = 25; -- Self Explaining
    TextColor = Color3.fromRGB(255,255,255); -- Self Explaining
    BgColor = Color3.fromRGB(69,69,69); -- Self Explaining
    
}) 


AutoClickEnabled = false
AutoRebirthEnabled = false 


b:Toggle("Auto Click",function(bool)
    shared.toggle = bool
AutoClickEnabled  = bool
end)


b:Toggle("Auto Rebirth",function(bool)
    shared.toggle = bool
AutoRebirthEnabled  = bool
end)



spawn(function()
    while wait() do
        if AutoClickEnabled == true then
            game:GetService("ReplicatedStorage").rbxts_include.node_modules.net.NetManagedInstances["e854a58f-65fe-4f31-8f81-43e6481ea348"]:FireServer() -- click
        end
    end
    end)
        
        
        spawn(function()
    while wait() do
        if AutoRebirthEnabled == true then
          -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohNumber1 = 0

game:GetService("ReplicatedStorage").rbxts_include.node_modules.net.NetManagedInstances["d18462d8-90a0-477d-b7dc-aa4f58846628"]:FireServer(ohNumber1)
        end
    end
    end)
        








--[[
How to refresh a dropdown:
1)Create the dropdown and save it in a variable
local yourvariable = b:Dropdown("Hi",yourtable,function(a)
    print(a)
end)
2)Refresh it using the function
yourvariable:Refresh(yourtable)
How to refresh a label:
1)Create your label and save it in a variable
local yourvariable = b:Label("Pretty Useless NGL",{
    TextSize = 25; -- Self Explaining
    TextColor = Color3.fromRGB(255,255,255);
    BgColor = Color3.fromRGB(69,69,69);
})
2)Refresh it using the function
yourvariable:Refresh("Hello") It will only change the text ofc
]]
